// <auto-generated />
namespace norris.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class vote_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vote_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201407091010308_vote_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
