// <auto-generated />
namespace norris.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changed_comments_context : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_comments_context));
        
        string IMigrationMetadata.Id
        {
            get { return "201407111136213_changed_comments_context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
